# Generated by Django 5.1.4 on 2025-01-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favouriteartist",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="favouritetrack",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterUniqueTogether(
            name="favouriteartist",
            unique_together={("user_id", "artist_id")},
        ),
        migrations.AlterUniqueTogether(
            name="favouritetrack",
            unique_together={("user_id", "track_id")},
        ),
    ]
