# Generated by Django 5.1.4 on 2025-01-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_user_id_favouriteartist_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favouriteartist",
            old_name="artist_id",
            new_name="spotify_artist_id",
        ),
        migrations.RenameField(
            model_name="favouritetrack",
            old_name="track_id",
            new_name="spotify_track_id",
        ),
        migrations.AlterUniqueTogether(
            name="favouriteartist",
            unique_together={("user", "spotify_artist_id")},
        ),
        migrations.AlterUniqueTogether(
            name="favouritetrack",
            unique_together={("user", "spotify_track_id")},
        ),
    ]
